version: '1.0'

services:
  healthera-nginx:
    image: jwilder/nginx-proxy
    container_name: healthera-nginx
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker/nginx/nginx-conf:/etc/nginx/conf.d
    depends_on:
      - healthera-api
      - rabbitmq
      - sqsqueue

  healthera-api:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    container_name: healthera-api
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - rabbitmq
      - sqsqueue
      - mongodb
    environment:
      - RABBITMQ_URL=${RABBITMQ_ENDPOINT}
    networks:
      - app-network
    volumes:
      - .:/usr/src/app

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network

  sqsqueue:
    image: localstack/localstack
    container_name: sqs
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
    networks:
      - app-network

  mongodb:
    container_name: mongodb
    build:
      context: ./mongo
      dockerfile: Dockerfile
    ports:
      - '27017:27017'
    volumes:
      - ./mongodb/mongo_data:/data/db
    networks:
      - app-network

volumes:
  rabbitmq_data:
    driver: local

networks:
  app-network:
    driver: bridge